Sibenice
iiskodova/pyladies pull request #11
Opened 2022-11-14 19:20 UTC by iiskodova

2022-11-15 07:40 UTC, kristiankralovic commented on lekce7/obrazky.py
> +    stages = ['''
Pekná myšlienka dať obrázky do poľa. :+1:

2022-11-15 08:04 UTC, kristiankralovic commented on lekce7/hangman2.py
> +    word = get_word()
Riadky 50, 51 a 53, 54 sa ti zbytočne opakujú. Pri návrhu funkcie sa vždy snaž vyhnúť zbytočnému opakovaniu. Často je to znak že by sa opakujúca časť kódu dala presunúť do samostatnej funkcie. V tomto prípade stačí kúsok upraviť podmienku pre while cyklus (tak ako je teraz to nebude fungovať). Môžeš znova použiť ` while True:`. Získať slovo, zavolať funkciu play, po ukončení funkcie main získať input a v prípade že je input iný ako A tak breaknuť cyklus.

2022-11-15 08:04 UTC, kristiankralovic commented on lekce7/hangman2.py
> +    while input('Chceš hrát znovu? (A/N): ').upper == 'A':
upper()

2022-11-15 08:13 UTC, kristiankralovic commented on lekce7/hangman2.py
> +    print(display_hangman(tries))
Opakujúce sa riadky. Skúsil by som to hodiť do nejakej funkcie npr. `print_status(tries, word_completion)`.

2022-11-15 08:20 UTC, kristiankralovic commented on lekce7/hangman2.py
> +                word_as_list = list(word_completion)
Riadok 31 až 35 by som vyhodil do samostatnej funkcie.

2022-11-15 08:24 UTC, kristiankralovic requested changes
Veľmi pekné, len doladiť drobnosti. :abacus: .

2022-11-16 14:46 UTC, iiskodova commented on lekce7/hangman2.py
> +    word = get_word()
mně ten while cyklus funguje, zeptá se to po hře jestli chci hrát dál a když dám a tak to spustí novou hru, když dám n tak se program ukončí. proč by neměl fungovat?

2022-11-17 11:01 UTC, kristiankralovic commented on lekce7/hangman2.py
> +    word = get_word()
Tak ako to máš teraz to nebude fungovať, pretože chýba () na riadku 52. U seba to asi máš opravené a preto ti to funguje. Ale nerieiš to opakujúci sa kód.

2022-11-19 19:52 UTC, merged