Ukoly lekce6
iiskodova/pyladies pull request #4
Opened 2022-11-01 08:56 UTC by iiskodova

2022-11-02 07:25 UTC, kristiankralovic commented on lekce6/rodne_cislo.py
> +
Bolo by dobré celú funkcionalitu hodiť do funkcii a použiť funkciu main, ktorá načíta vstup, a potom zavolá jednotlivé funkcie na kontrolu. Ako vytvoriť funkciu main nájdeš tu: https://realpython.com/python-main-function/#a-basic-python-main .

2022-11-02 07:42 UTC, kristiankralovic commented on lekce6/rodne_cislo.py
> +        if i == 6 and rodne_cislo[i] =='/':
Toto v prípadne že je zadané niečo ako 123456/abcd spôsobí, že funkcia neodchytí zlý vstup a vypíše True. 
Opraviť sa to dá jednoducho tak že `if i == 6 and rodne_cislo[i] != '/'` bude vracať False, a na riadok 9 pridáš `return True`.

2022-11-02 07:47 UTC, kristiankralovic commented on lekce6/rodne_cislo.py
> +    rc = []
Dĺžku vstupu kontroluješ zbytočne zložito. V podstate by ti stačilo len použiť funkciu len() na input, pretože v vo funkcii formát_check() už kontroluješ formát vstupu. Nemusíš tu kontrolovať či jednotlivé znaky sú číslice. Skús funkciu, čo najviac zjednodušiť a v prípade, že si nebudeš vedieť rady, napíš mi na Slack.

2022-11-02 07:52 UTC, kristiankralovic commented on lekce6/rodne_cislo.py
> +    gender = ''
Toto sa tiež dá zjednodušiť. Premenná gender v tejto funkcii je zbytočná. Možeš rovno urobiť toto:
`    if int(rodne_cislo[2]) >= 5:
        return 'žena'
    else:
        return 'muž'

2022-11-02 07:54 UTC, kristiankralovic commented on lekce6/rodne_cislo.py
> +    month = []
Táto inicializácia month = [] je zbytočná.

2022-11-02 07:55 UTC, kristiankralovic requested changes
Rodné číslo máš skontrolované. Uprav prosím veci ktoré som tu napísal. Ak si nevieš s niečim rady, napíš mi na Slack.

2022-11-05 15:15 UTC, iiskodova reviewed
prepsano

2022-11-05 15:17 UTC, merged